name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: SSH into Server and Deploy
        run: |
          expect <<EOF
          spawn ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          expect "password:"
          send "${{ secrets.SSH_PASSWORD }}\r"
          expect "$ "
          send "cd /home/${{ secrets.SSH_USER }}/public_html/news-hub-api/\r"
          send "git pull origin main\r"
          send "composer2 install --no-interaction --prefer-dist --optimize-autoloader\r"
          send "composer2 update --no-interaction\r"
          
          # Ensure .env file exists
          send "cp .env.example .env\r"

          # Inject API Keys from GitHub Secrets
          send "echo '\nNEWSAPI_API_KEY=${{ secrets.NEWSAPI_API_KEY }}' >> .env\r"
          send "echo 'GUARDIAN_API_KEY=${{ secrets.GUARDIAN_API_KEY }}' >> .env\r"
          send "echo 'NYT_API_KEY=${{ secrets.NYT_API_KEY }}' >> .env\r"

          # Run Laravel Migrations & Seeders
          send "php artisan migrate --force\r"
          send "php artisan migrate:fresh --seed --force\r"

          # Generate application key
          send "php artisan key:generate\r"

          # Optimize Laravel
          send "composer2 dump-autoload\r"

          # Run Laravel Tests
          send "php artisan test\r"

          send "exit\r"
          expect eof
          EOF
