name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: SSH into Server and Deploy
        run: |
          expect <<EOF
          spawn ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          expect "password:"
          send "${{ secrets.SSH_PASSWORD }}\r"
          expect "$ "
          send "cd /var/www/news-hub-api && git pull origin main\r"
          send "composer install --no-interaction --prefer-dist --optimize-autoloader\r"
          send "composer update --no-interaction\r"
          send "if [ ! -f .env ]; then cp .env.example .env; fi\r"
          send "echo '\nNEWSAPI_API_KEY=${{ secrets.NEWSAPI_API_KEY }}' >> .env\r"
          send "echo 'GUARDIAN_API_KEY=${{ secrets.GUARDIAN_API_KEY }}' >> .env\r"
          send "echo 'NYT_API_KEY=${{ secrets.NYT_API_KEY }}' >> .env\r"
          send "php artisan migrate --force\r"
          send "php artisan migrate:fresh --seed --force\r"
          send "php artisan key:generate\r"
          send "composer dump-autoload\r"
          send "php artisan test\r"
          send "exit\r"
          expect eof
          EOF
